import {
  ALTERNATE,
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  FEED_IN,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  ORGANISER_ACCEPTANCE,
  QUALIFIER,
  REGISTERED,
  SPECIAL_EXEMPT,
  UNGROUPED,
  UNPAIRED,
  WILDCARD,
  WITHDRAWN,
} from './entryStatusValues';
import { EntryStatusUnion } from '@Types/tournamentTypes';

// primitive entry-status consts are generated from EntryStatusEnum (see
// entryStatusValues.ts); the semantic groupings below are hand-authored.
export * from './entryStatusValues';

export const EQUIVALENT_ACCEPTANCE_STATUSES: EntryStatusUnion[] = [
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  JUNIOR_EXEMPT,
  ORGANISER_ACCEPTANCE,
  SPECIAL_EXEMPT,
];
export const DRAW_SPECIFIC_STATUSES: EntryStatusUnion[] = [FEED_IN, LUCKY_LOSER, QUALIFIER];

export const DIRECT_ENTRY_STATUSES: EntryStatusUnion[] = [
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  FEED_IN,
  JUNIOR_EXEMPT,
  ORGANISER_ACCEPTANCE,
  SPECIAL_EXEMPT,
  WILDCARD,
];

export const STRUCTURE_SELECTED_STATUSES: EntryStatusUnion[] = [
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  QUALIFIER,
  ORGANISER_ACCEPTANCE,
  SPECIAL_EXEMPT,
  WILDCARD,
];

export const VALID_ENTRY_STATUSES: EntryStatusUnion[] = [
  ALTERNATE,
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  FEED_IN,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  ORGANISER_ACCEPTANCE,
  QUALIFIER,
  REGISTERED,
  SPECIAL_EXEMPT,
  UNGROUPED,
  UNPAIRED,
  WILDCARD,
  WITHDRAWN,
];

export const entryStatusConstants = {
  ALTERNATE,
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  DIRECT_ENTRY_STATUSES,
  DRAW_SPECIFIC_STATUSES,
  EQUIVALENT_ACCEPTANCE_STATUSES,
  FEED_IN,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  ORGANISER_ACCEPTANCE,
  QUALIFIER,
  REGISTERED,
  SPECIAL_EXEMPT,
  STRUCTURE_SELECTED_STATUSES,
  UNGROUPED,
  UNPAIRED,
  VALID_ENTRY_STATUSES,
  WILDCARD,
  WITHDRAWN,
} as const;
