import mocksEngine from '@Assemblies/engines/mock';
import tournamentEngine from '@Engines/syncEngine';
import { describe, expect, it } from 'vitest';
import addFormats from 'ajv-formats';
import fs from 'fs-extra';
import Ajv from 'ajv';

// constants
import { DOMINANT_DUO } from '@Constants/tieFormatConstants';
import { INDIVIDUAL } from '@Constants/participantConstants';
import { NOT_BEFORE } from '@Constants/timeItemConstants';
import { OFFICIAL } from '@Constants/participantRoles';
import { TEAM } from '@Constants/eventConstants';
import {
  COMPASS,
  CURTIS_CONSOLATION,
  FEED_IN,
  FEED_IN_CHAMPIONSHIP_TO_SF,
  FIRST_MATCH_LOSER_CONSOLATION,
  FIRST_ROUND_LOSER_CONSOLATION,
  MODIFIED_FEED_IN_CHAMPIONSHIP,
  ROUND_ROBIN,
  ROUND_ROBIN_WITH_PLAYOFF,
} from '@Constants/drawDefinitionConstants';

const ajv = new Ajv({ allowUnionTypes: true, verbose: true, allErrors: true });
ajv.addFormat('date-time', (dateTime: any) => {
  if (typeof dateTime === 'object') dateTime = dateTime.toISOString();
  return !Number.isNaN(Date.parse(dateTime));
});
addFormats(ajv);

const schema = JSON.parse(
  fs.readFileSync('./src/global/schema/tournament.schema.json', {
    encoding: 'utf8',
  }),
);
const validate = ajv.compile(schema);

const sourcePath = './src/tests/testHarness';
// `.includes`, not `indexOf(...) === undefined`. `indexOf` returns a NUMBER, so the old
// `filename.indexOf('.8') === undefined` was always false and `filenames` was always EMPTY —
// `it.each([])` registers no tests and vitest does not complain, so this suite reported green
// while validating none of the 16 fixtures. The read path below was wrong too
// (`src/global/testHarness`, which does not exist), so either bug alone was fatal.
// The suffix is `.codes.json` (renamed from `.tods.json`); this filter, `listFixtures` in
// corpus/fixtureSources.ts and anonymizeTournamentRecord.test.ts must all change together.
const filenames: any[] = fs.readdirSync(sourcePath).filter((filename) => filename.endsWith('.codes.json'));

// Guard the guard: if the glob ever goes empty again, fail loudly instead of silently passing.
it('finds CODES files to validate', () => {
  expect(filenames.length).toBeGreaterThan(10);
});

it.each(filenames)('can validate all CODES files in testHarness directory', (filename) => {
  const data = JSON.parse(
    fs.readFileSync(`${sourcePath}/${filename}`, {
      encoding: 'utf8',
    }),
  );
  const result = validate(data);

  // to document pattern of use
  if (validate.errors) {
    const errors = ajv.errorsText(validate.errors, {
      dataVar: 'config',
    });
    console.log({ filename }, errors);
  }

  expect(result).toEqual(true);
});

const mockProfiles = [
  { drawProfiles: [{ drawSize: 32, drawType: MODIFIED_FEED_IN_CHAMPIONSHIP }] },
  { drawProfiles: [{ drawSize: 32, drawType: FIRST_ROUND_LOSER_CONSOLATION }] },
  { drawProfiles: [{ drawSize: 32, drawType: FIRST_MATCH_LOSER_CONSOLATION }] },
  { drawProfiles: [{ drawSize: 32, drawType: FEED_IN_CHAMPIONSHIP_TO_SF }] },
  { drawProfiles: [{ drawSize: 32, drawType: ROUND_ROBIN_WITH_PLAYOFF }] },
  { drawProfiles: [{ drawSize: 32, drawType: CURTIS_CONSOLATION }] },
  { drawProfiles: [{ drawSize: 32, drawType: ROUND_ROBIN }] },
  { drawProfiles: [{ drawSize: 32, drawType: COMPASS }] },
  { drawProfiles: [{ drawSize: 48, drawType: FEED_IN }] },
];

it.each(mockProfiles)('can validate tournaments generated by mocksEngine', (mockProfile) => {
  const { tournamentRecord } = mocksEngine.generateTournamentRecord(mockProfile);

  const result = validate(tournamentRecord);

  // to document pattern of use
  if (validate.errors) {
    const errors = ajv.errorsText(validate.errors, {
      dataVar: 'config',
      separator: ';',
    });
    console.log(errors);
    console.log(mockProfile);
    console.log(Object.keys(tournamentRecord.events[0].drawDefinitions[0].structures[1]));
    console.log(
      tournamentRecord.participants.map((p, i) => [i, p.person.addresses[0].countryCode]),
      tournamentRecord.events[0].drawDefinitions[0].structures[1].matchUps.map((m) => m.drawPositions),
    );
  }
  expect(result).toEqual(true);
});

/**
 * `MatchUp` is CLOSED, and until this test existed the schema had no `schedule` at all. 5.0.0 made
 * `matchUp.schedule` the canonical written shape (NATIVE write mode, the default) and the schema
 * never followed, so a record with ONE scheduled matchUp failed validation while every profile
 * above stayed green: none of them schedules anything. The same class of gap hid `Court.venueId`,
 * which `addCourt` writes on every court.
 *
 * So this test writes EVERY first-class schedule attribute the engine knows how to write, through
 * the public methods, then validates the RAW record. It also pins the schema's `MatchUpSchedule`
 * property set to exactly the attributes observed on the record: a field the engine writes but the
 * schema omits fails validation, and a field the schema declares but this test never exercises
 * fails the equality, so the declaration cannot drift in either direction silently.
 */
describe('first-class schedule attributes validate against the schema', () => {
  const START_DATE = '2026-10-01';
  const VENUE_ID = 'schema-venue';
  const SINGLES_DRAW = 'schema-singles';
  const TEAM_DRAW = 'schema-team';

  const rawRecord = () => tournamentEngine.getTournament().tournamentRecord;
  const rawMatchUp = (matchUpId: string) =>
    rawRecord()
      .events.flatMap((e: any) => e.drawDefinitions ?? [])
      .flatMap((d: any) => d.structures ?? [])
      .flatMap((s: any) => s.matchUps ?? [])
      .find((m: any) => m.matchUpId === matchUpId);

  it('accepts a record whose matchUps carry every written schedule attribute', () => {
    const { tournamentRecord } = mocksEngine.generateTournamentRecord({
      venueProfiles: [{ courtsCount: 4, startTime: '08:00', endTime: '21:00', venueId: VENUE_ID }],
      drawProfiles: [
        { drawId: SINGLES_DRAW, drawSize: 8 },
        { drawId: TEAM_DRAW, drawSize: 4, eventType: TEAM, tieFormatName: DOMINANT_DUO },
      ],
      startDate: START_DATE,
      endDate: '2026-10-03',
      setState: true,
    });
    const { tournamentId } = tournamentRecord;
    const { courts } = tournamentEngine.getVenuesAndCourts();
    const { matchUps } = tournamentEngine.allTournamentMatchUps();
    const singles = matchUps.find(
      (m: any) => m.drawId === SINGLES_DRAW && m.roundNumber === 1 && m.sides?.every((s: any) => s?.participantId),
    );
    const team = matchUps.find((m: any) => m.drawId === TEAM_DRAW && m.matchUpType === TEAM);
    expect(singles && team).toBeTruthy();
    const sideParticipantIds = singles.sides.map((s: any) => s.participantId);

    const { participant: official } = tournamentEngine.addParticipant({
      participant: {
        person: { personId: 'schema-chair-umpire', standardFamilyName: 'Umpire', standardGivenName: 'Chair' },
        participantType: INDIVIDUAL,
        participantRole: OFFICIAL,
      },
      returnParticipant: true,
      tournamentId,
    });
    const bystander = tournamentEngine
      .getParticipants({ participantFilters: { participantTypes: [INDIVIDUAL] } })
      .participants.find((p: any) => !sideParticipantIds.includes(p.participantId));

    const { matchUpId, drawId } = singles;
    const steps: [string, any][] = [
      [
        'addMatchUpScheduleItems',
        tournamentEngine.addMatchUpScheduleItems({
          schedule: {
            scheduledDate: START_DATE,
            scheduledTime: '09:00',
            venueId: VENUE_ID,
            courtId: courts[0].courtId,
            courtOrder: 1,
            courtAnnotation: 'Show court',
            timeModifiers: [NOT_BEFORE],
          },
          matchUpId,
          drawId,
        }),
      ],
      [
        'setMatchUpHomeParticipantId',
        tournamentEngine.setMatchUpHomeParticipantId({ homeParticipantId: sideParticipantIds[0], matchUpId, drawId }),
      ],
      [
        'assignMatchUpScorekeeper',
        tournamentEngine.assignMatchUpScorekeeper({ participantId: bystander.participantId, matchUpId, drawId }),
      ],
      [
        'assignMatchUpTimekeeper',
        tournamentEngine.assignMatchUpTimekeeper({ participantId: bystander.participantId, matchUpId, drawId }),
      ],
      [
        'addMatchUpOfficial',
        tournamentEngine.addMatchUpOfficial({ participantId: official.participantId, tournamentId, matchUpId, drawId }),
      ],
      [
        'setMatchUpScheduleLock',
        tournamentEngine.setMatchUpScheduleLock({
          lock: {
            attributes: ['courtId', 'scheduledTime'],
            lockedAt: '2026-09-30T12:00:00.000Z',
            lockedBy: 'tournament-director',
            reason: 'marquee match',
          },
          matchUpId,
          drawId,
        }),
      ],
      [
        'setMatchUpCalledAt',
        tournamentEngine.setMatchUpCalledAt({ calledAt: '2026-10-01T09:05:00.000Z', matchUpId, drawId }),
      ],
      [
        'setMatchUpStatus',
        tournamentEngine.setMatchUpStatus({
          outcome: mocksEngine.generateOutcomeFromScoreString({ scoreString: '6-1 6-1', winningSide: 1 }).outcome,
          matchUpId,
          drawId,
        }),
      ],
      [
        'allocateTeamMatchUpCourts',
        tournamentEngine.allocateTeamMatchUpCourts({
          courtIds: [courts[1].courtId, courts[2].courtId],
          matchUpId: team.matchUpId,
          drawId: TEAM_DRAW,
        }),
      ],
    ];
    for (const [name, result] of steps) {
      expect({ name, error: result?.error, success: result?.success }).toEqual({
        name,
        error: undefined,
        success: true,
      });
    }

    // Guard the guard: a green validation proves nothing unless the RAW record carries the fields.
    const written = rawMatchUp(matchUpId).schedule;
    expect(written.timeItems).toBeUndefined();
    expect(written.lock).toEqual({
      attributes: ['courtId', 'scheduledTime'],
      lockedAt: '2026-09-30T12:00:00.000Z',
      lockedBy: 'tournament-director',
      reason: 'marquee match',
    });
    expect(typeof written.scoredTime).toEqual('string');
    const teamWritten = rawMatchUp(team.matchUpId).schedule;
    expect(teamWritten.allocatedCourts.map((c: any) => Object.keys(c).sort())).toEqual([
      ['courtId', 'venueId'],
      ['courtId', 'venueId'],
    ]);
    const courtsInRecord = rawRecord().venues.flatMap((v: any) => v.courts ?? []);
    expect(courtsInRecord.length).toEqual(4);
    expect(courtsInRecord.every((c: any) => c.venueId === VENUE_ID)).toEqual(true);

    // The declaration is pinned to the written set, in BOTH directions.
    const observed = new Set([...Object.keys(written), ...Object.keys(teamWritten)]);
    expect([...Object.keys(schema.definitions.MatchUpSchedule.properties)].sort()).toEqual([...observed].sort());

    const result = validate(rawRecord());
    if (validate.errors) console.log(ajv.errorsText(validate.errors, { dataVar: 'record', separator: ';\n' }));
    expect(result).toEqual(true);
  });
});
