import { addFinishingRounds } from '@Assemblies/generators/drawDefinitions/addFinishingRounds';
import { getMappedStructureMatchUps } from '@Query/matchUps/getMatchUpsMap';
import { getAllDrawMatchUps } from '@Query/matchUps/drawMatchUps';
import { positionTargets } from '@Query/matchUp/positionTargets';

// constants and types
import { MISSING_DRAW_DEFINITION } from '@Constants/errorConditionConstants';
import { LOSER, WIN_RATIO } from '@Constants/drawDefinitionConstants';
import { DrawDefinition } from '@Types/tournamentTypes';
import { MatchUpsMap } from '@Types/factoryTypes';
import { HydratedMatchUp } from '@Types/hydrated';

type AddGoesToArgs = {
  inContextDrawMatchUps?: HydratedMatchUp[];
  drawDefinition: DrawDefinition;
  matchUpsMap?: MatchUpsMap;
};
export function addGoesTo({ inContextDrawMatchUps, drawDefinition, matchUpsMap }: AddGoesToArgs) {
  if (!drawDefinition) return { error: MISSING_DRAW_DEFINITION };

  const goesToMap = { loserMatchUpIds: {}, winnerMatchUpIds: {} };

  // Both args are optional, so all four combinations must work. Previously the map was
  // only ever built inside `if (!inContextDrawMatchUps)`, which meant the one combination
  // an integrator would most naturally reach for — "here are the matchUps I already
  // flattened, enrich them" — dereferenced an undefined map and threw a bare
  // `Cannot read properties of undefined` out of getMappedStructureMatchUps.
  //
  // Resolve each independently, and use `??=` so a caller-supplied array is never
  // replaced by a freshly-flattened one: callers pass their own array precisely because
  // they intend THAT array to be mutated in place.
  if (!inContextDrawMatchUps || !matchUpsMap) {
    const resolved = getAllDrawMatchUps({ inContext: true, drawDefinition, matchUpsMap });
    inContextDrawMatchUps ??= resolved.matchUps;
    matchUpsMap ??= resolved.matchUpsMap;
  }

  const hasFinishingPositionRanges = matchUpsMap?.drawMatchUps.some((m) => m.finishingPositionRange);

  // NOTE: handles drawDefinitions in TODS files not generated by the factory
  // IF: there is only one structure present... as is the case with tods-xls-converter
  if (
    !hasFinishingPositionRanges &&
    drawDefinition?.structures?.length === 1 &&
    !drawDefinition?.structures[0].structures
  ) {
    const matchUps = matchUpsMap?.drawMatchUps ?? [];
    addFinishingRounds({ matchUps });
  }

  (inContextDrawMatchUps ?? [])
    .filter(({ collectionId }) => !collectionId)
    .forEach((inContextMatchUp) => {
      const { matchUpId, structureId } = inContextMatchUp;
      const targetData = positionTargets({
        inContextDrawMatchUps,
        drawDefinition,
        matchUpId,
      });
      const { winnerMatchUp, loserMatchUp } = targetData.targetMatchUps;
      const winnerMatchUpId = winnerMatchUp?.matchUpId;
      const loserMatchUpId = loserMatchUp?.matchUpId;

      const matchUps = getMappedStructureMatchUps({
        matchUpsMap,
        structureId,
      });
      const matchUp = matchUps.find((matchUp) => matchUp.matchUpId === matchUpId);

      if (matchUp) {
        if (winnerMatchUpId) {
          goesToMap.winnerMatchUpIds[matchUp.matchUpId] = winnerMatchUpId;
          Object.assign(matchUp, { winnerMatchUpId });
          Object.assign(inContextMatchUp, { winnerMatchUpId });
        }
        if (loserMatchUpId) {
          goesToMap.loserMatchUpIds[matchUp.matchUpId] = loserMatchUpId;
          inContextMatchUp.loserMatchUpId = loserMatchUpId;
          matchUp.loserMatchUpId = loserMatchUpId;

          if (inContextMatchUp.finishingPositionRange) {
            const loserRange = loserMatchUp.finishingPositionRange && [
              ...inContextMatchUp.finishingPositionRange.loser,
              ...loserMatchUp.finishingPositionRange.loser,
            ];
            const loser = loserRange && [Math.min(...loserRange), Math.max(...loserRange)];
            inContextMatchUp.finishingPositionRange.loser = loser;
            matchUp.finishingPositionRange.loser = loser;
          }
        }
      }
    });

  return { inContextDrawMatchUps, goesToMap };
}

/**
 * Does the draw STORE the edges `addGoesTo` derives — `winnerMatchUpId` and `loserMatchUpId`?
 *
 * A draw the factory generated does: generation, playoff generation and `attachStructures` all write
 * them. A record that came from somewhere else may not — an older record, or a file the factory did
 * not produce — and the exit cascade reads the STORED ids (`hasPropagatedExitDownstream`,
 * `getExitWinningSide`, `getHeldExit`), so on such a draw it decides differently. Measured
 * 2026-10-01: the same hundred matrix cells played on draws with the ids stripped ended in a
 * different draw 44 times when nothing restored them.
 *
 * This is the cheap question, asked of the stored matchUps alone, that says whether the expensive
 * answer (`addGoesTo`: a hydration and a `positionTargets` per matchUp) is needed at all:
 *
 *  - an elimination structure with more than one round holds a matchUp with a `winnerMatchUpId`;
 *  - a structure a LOSER link leaves holds a matchUp with a `loserMatchUpId`.
 *
 * It asks whether a structure has ANY, not whether it has all: a final has no winner target, and
 * `removeStructure` deletes the ids that pointed into what it removed. `false` is the safe answer —
 * it costs a derivation, never a wrong edge.
 */
export function hasStoredGoesTo({ drawDefinition }: { drawDefinition: DrawDefinition }): boolean {
  const loserSources = new Set(
    (drawDefinition.links ?? []).filter((link) => link.linkType === LOSER).map((link) => link.source?.structureId),
  );

  return (drawDefinition.structures ?? []).every((structure) => {
    const matchUps = structure.matchUps ?? [];
    if (loserSources.has(structure.structureId) && !matchUps.some((matchUp) => matchUp.loserMatchUpId)) return false;
    if (structure.finishingPosition === WIN_RATIO || structure.structures) return true;
    const rounds = new Set(matchUps.map((matchUp) => matchUp.roundNumber));
    return rounds.size < 2 || matchUps.some((matchUp) => matchUp.winnerMatchUpId);
  });
}

/** Give a draw that does not store its edges the edges; a draw that does is left alone. */
export function ensureGoesTo({ drawDefinition }: { drawDefinition: DrawDefinition }) {
  if (!hasStoredGoesTo({ drawDefinition })) addGoesTo({ drawDefinition });
}
