module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Competition Factory',
      items: [
        'introduction',
        'data-standards',
        'time-capsule',
        {
          type: 'category',
          label: 'TMX Example',
          items: [
            'tmx',
            'tmx/overview',
            'tmx/participants',
            'tmx/events-categories',
            'tmx/draws',
            'tmx/matchups',
            'tmx/venues-scheduling',
            'tmx/browser-console',
            'tmx/factory-server',
            'tmx/tmx-api-surface',
          ],
        },
        'installation',
        'acknowledgements',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'category',
          label: 'Tournament Setup',
          items: ['concepts/registration-profile', 'concepts/tournament-tier'],
        },
        {
          type: 'category',
          label: 'Format Wizard',
          collapsed: true,
          items: [
            'concepts/format-wizard/engine',
            'concepts/format-wizard/distribution',
            'concepts/format-wizard/example',
          ],
        },
        {
          type: 'category',
          label: 'Participants',
          items: ['concepts/participants', 'concepts/participant-context', 'concepts/scaleItems'],
        },
        {
          type: 'category',
          label: 'Events',
          items: [
            'concepts/events/events-overview',
            'concepts/events/categories',
            'concepts/events/entries',
            'concepts/events/flights',
          ],
        },
        {
          type: 'category',
          label: 'Draws',
          items: [
            'concepts/draws-overview',
            'concepts/draw-types',
            {
              type: 'category',
              label: 'Draw Type Details',
              collapsed: true,
              items: [
                'concepts/draw-types/single-elimination',
                'concepts/draw-types/double-elimination',
                'concepts/draw-types/round-robin',
                'concepts/draw-types/round-robin-with-playoff',
                'concepts/draw-types/compass',
                'concepts/draw-types/olympic',
                'concepts/draw-types/feed-in',
                'concepts/draw-types/consolation-draws',
                'concepts/draw-types/ad-hoc',
                'concepts/draw-types/drawmatic',
                'concepts/draw-types/page-playoff',
                'concepts/draw-types/playoff',
                'concepts/draw-types/lucky-draw',
                'concepts/draw-types/adaptive',
                'concepts/draw-types/swiss',
              ],
            },
            'concepts/draw-links',
            'concepts/draft-draws',
            'concepts/seed-withdrawal-cascade',
            'concepts/exit-profiles',
            'concepts/finishing-positions',
            'concepts/actions',
          ],
        },
        {
          type: 'category',
          label: 'matchUps',
          items: [
            'concepts/matchup-overview',
            'concepts/matchup-context',
            'concepts/matchup-filtering',
            'concepts/tieMatchUp',
            'concepts/lineUp',
            'concepts/tieFormat',
          ],
        },
        {
          type: 'category',
          label: 'Scheduling',
          items: [
            'concepts/scheduling-overview',
            'concepts/venues-courts',
            'concepts/scheduling-policy',
            'concepts/scheduling-profile',
            'concepts/schedule-scenarios',
            'concepts/automated-scheduling',
            'concepts/pro-scheduling',
            'concepts/scheduling-conflicts',
            'concepts/date-time-handling',
          ],
        },
        {
          type: 'category',
          label: 'Publishing',
          items: [
            'concepts/publishing/publishing-overview',
            'concepts/publishing/publishing-events',
            'concepts/publishing/publishing-seeding',
            'concepts/publishing/publishing-order-of-play',
            'concepts/publishing/publishing-participants',
            'concepts/publishing/publishing-embargo',
            'concepts/publishing/publishing-data-subscriptions',
            'concepts/publishing/publishing-workflows',
          ],
        },
        {
          type: 'category',
          label: 'Record Data',
          items: ['concepts/accessors', 'concepts/timeItems', 'concepts/extensions'],
        },
        {
          type: 'category',
          label: 'Policies',
          items: [
            'concepts/policies',
            {
              type: 'category',
              label: 'Positioning & Seeding',
              items: [
                'policies/positionActions',
                'policies/positioningSeeds',
                'policies/seedingPolicy',
                'policies/avoidance',
              ],
            },
            {
              type: 'category',
              label: 'Draw Shape',
              items: [
                'policies/draws',
                'policies/maxParticipants',
                'policies/feedInPolicy',
                'policies/feedPolicy',
                'policies/consolationPolicy',
                'policies/progressionPolicy',
              ],
            },
            {
              type: 'category',
              label: 'matchUps & Rounds',
              items: [
                'policies/matchUpActions',
                'policies/roundNaming',
                'policies/tallyPolicy',
                'policies/roundRobinTallyPolicy',
              ],
            },
            {
              type: 'category',
              label: 'Scoring & Ranking',
              items: ['policies/scoringPolicy', 'policies/rankingPolicy', 'policies/competitiveBands'],
            },
            {
              type: 'category',
              label: 'Eligibility & Compliance',
              items: ['policies/participantPolicy', 'policies/sanctioningPolicy', 'policies/competitionPolicy'],
            },
            {
              type: 'category',
              label: 'Operations',
              items: ['policies/scheduling', 'policies/printPolicy'],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'State Engines',
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'engines/state-engines',
        },
        {
          type: 'category',
          label: 'Composition & Configuration',
          items: [
            'engines/engine-methods',
            'engines/typed-engine',
            'engines/custom-engines',
            'engines/declaration-engine',
            'engines/global-state',
          ],
        },
        {
          type: 'category',
          label: 'Reading State',
          items: ['engines/query-facade', 'engines/unwrap', 'engines/state-inspection', 'engines/get-tally'],
        },
        {
          type: 'category',
          label: 'Mutating State',
          items: [
            'engines/mutation-engines',
            'engines/fluent-builders',
            'engines/engine-middleware',
            'engines/subscriptions',
            'engines/dry-run-explain',
            'engines/json-patch',
            'concepts/mutation-locks',
          ],
        },
        {
          type: 'category',
          label: 'Diagnostics & Helpers',
          items: [
            'engines/engine-logging',
            'engines/factory-errors',
            'engines/policy-composer',
            'engines/migrate-tournament-record',
          ],
        },
        {
          type: 'category',
          label: 'Scale Engine',
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'scale-engine/scale-engine-overview',
            },
            'scale-engine/scale-engine-api',
            'scale-engine/ranking-points-pipeline',
            'scale-engine/quality-win-points',
            'scale-engine/aggregation',
          ],
        },
        {
          type: 'category',
          label: 'Scoring Engine',
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'scoring-engine/scoring-engine-overview',
            },
            'scoring-engine/scoring-engine-api',
            'scoring-engine/event-handlers',
            'scoring-engine/format-support',
            'scoring-engine/visualization-applications',
          ],
        },
        {
          type: 'category',
          label: 'Availability Engine',
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'availability-engine/availability-engine-overview',
            },
            'availability-engine/availability-engine-api',
            'availability-engine/event-system-and-validation',
            'availability-engine/block-types-and-algorithms',
            'availability-engine/ui-integration-scenarios',
          ],
        },
        {
          type: 'category',
          label: 'Draw Engine',
          items: ['engines/draw-engine-overview', 'apis/draw-engine-api'],
        },
        {
          type: 'category',
          label: 'Sanctioning Engine',
          items: ['engines/sanctioning-engine', 'engines/sanctioning-engine-design'],
        },
        {
          type: 'category',
          label: 'Officiating Engine',
          items: ['engines/officiating-engine'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Governors',
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'governors/governors-overview',
        },
        {
          type: 'category',
          label: 'Tournament & Events',
          items: [
            'governors/tournament-governor',
            'governors/competition-governor',
            'governors/event-governor',
            'governors/draws-governor',
            'governors/entries-governor',
          ],
        },
        {
          type: 'category',
          label: 'Generation',
          items: [
            'governors/generation-governor',
            'governors/generation/generateDrawDefinition',
            'governors/generation/drawMatic',
            'governors/generation/remapDrawDefinitionMatchUpIds',
          ],
        },
        {
          type: 'category',
          label: 'matchUps & Scoring',
          items: [
            'governors/matchup-governor',
            'governors/matchup-format-governor',
            'governors/tie-format-governor',
            'governors/score-governor',
          ],
        },
        {
          type: 'category',
          label: 'People & Ranking',
          items: ['governors/participant-governor', 'governors/ranking-governor'],
        },
        {
          type: 'category',
          label: 'Scheduling & Venues',
          items: ['governors/schedule-governor', 'governors/venue-governor'],
        },
        {
          type: 'category',
          label: 'Reporting & Querying',
          items: ['governors/query-governor', 'governors/publishing-governor', 'governors/report-governor'],
        },
        {
          type: 'category',
          label: 'Compliance & Officiating',
          items: ['governors/policy-governor', 'governors/sanctioning-governor', 'governors/officiating-governor'],
        },
        {
          type: 'category',
          label: 'Mocks & Practice',
          items: ['governors/mocks-governor', 'governors/practice-governor'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'tools/tools-overview',
        },
        'tools/make-deep-copy',
        'tools/structure-sort',
        'tools/json-to-csv',
        'tools/tools-api',
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [
        { type: 'doc', label: 'Overview', id: 'testing/testing-overview' },
        {
          type: 'category',
          label: 'mocksEngine',
          collapsed: false,
          items: [
            'testing/mocks-engine-overview',
            'testing/mocks-engine-getting-started',
            'testing/mocks-engine-tournament-generation',
            'testing/mocks-engine-participants',
            'testing/mocks-engine-outcomes',
            'testing/mocks-engine-league-profiles',
            'testing/mocks-engine-patterns',
          ],
        },
        'testing/factory-server',
      ],
    },
    {
      type: 'category',
      label: 'Data',
      items: [
        'constants',
        'types/typedefs',
        {
          type: 'category',
          label: 'Codes',
          items: ['codes/age-category', 'codes/matchup-format'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Release Notes & Migration',
      items: [
        'whats-new-6.0.0',
        'whats-new-5.0.0',
        {
          type: 'category',
          label: 'Migration Guides',
          items: ['migration-6.0.0', 'migration-5.0.0', 'migration-4.0.0', 'migration-3.0.0', 'migration'],
        },
      ],
    },
  ],
};
